treewide: Fix error cause a function declaration is deprecated
xiaomi_touch: Fix error cause a function declaration is deprecated

../kernel/drivers/input/touchscreen/mediatek/xiaomi/xiaomi_touch.c:136:37: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct class *get_xiaomi_touch_class()
                                    ^
                                     void
../kernel/drivers/input/touchscreen/mediatek/xiaomi/xiaomi_touch.c:141:36: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct device *get_xiaomi_touch_dev()
                                   ^
                                    void
2 errors generated.

Signed-off-by: Rama Bondan Prakoso <ramanarubp@gmail.com>

mtk_mcdi_governor: Fix a function declaration without a prototype is deprecated

../kernel/drivers/misc/mediatek/base/power/mcdi/mtk_mcdi_governor.c:197:5: error: a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
int get_cluster_off_token(cpu)
    ^
1 error generated.

Signed-off-by: Rama Bondan Prakoso <ramanarubp@gmail.com>

mtk: fm_drv_init: Fix a function declaration without a prototype is deprecated

../kernel/drivers/misc/mediatek/connectivity/common/common_detect/drv_init/fm_drv_init.c:24:42: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) mtk_wcn_fm_init()
                                         ^
                                          void
1 error generated.

Signed-off-by: Rama Bondan Prakoso <ramanarubp@gmail.com>

mtk: bluetooth_drv_init: Fix a function declaration without a prototype is deprecated

../kernel/drivers/misc/mediatek/connectivity/common/common_detect/drv_init/bluetooth_drv_init.c:24:49: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) mtk_wcn_stpbt_drv_init()
                                                ^
                                                 void
1 error generated.

Signed-off-by: Rama Bondan Prakoso <ramanarubp@gmail.com>

mtk: wlan_drv_init: Fix a function declaration without a prototype is deprecated

../kernel/drivers/misc/mediatek/connectivity/common/common_detect/drv_init/wlan_drv_init.c:23:49: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) mtk_wcn_wlan_gen4_init()
                                                ^
                                                 void
../kernel/drivers/misc/mediatek/connectivity/common/common_detect/drv_init/wlan_drv_init.c:29:49: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) mtk_wcn_wlan_gen3_init()
                                                ^
                                                 void
../kernel/drivers/misc/mediatek/connectivity/common/common_detect/drv_init/wlan_drv_init.c:35:49: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) mtk_wcn_wlan_gen2_init()
                                                ^
                                                 void
../kernel/drivers/misc/mediatek/connectivity/common/common_detect/drv_init/wlan_drv_init.c:41:48: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) mtk_wcn_wmt_wifi_init()
                                               ^
                                                void
4 errors generated.

Signed-off-by: Rama Bondan Prakoso <ramanarubp@gmail.com>

mi_opensource: Fix a function declaration without a prototype is deprecated

/kernel/drivers/misc/mi-memory/mi_opensource.c:2:25: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static void open_source ()
                        ^
                         void
1 error generated.

Signed-off-by: Rama Bondan Prakoso <ramanarubp@gmail.com>

mtk: gps_drv_init: Fix a function declaration without a prototype is deprecated

../kernel/drivers/misc/mediatek/connectivity/common/common_detect/drv_init/gps_drv_init.c:24:50: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) mtk_wcn_stpgps_drv_init()
                                                 ^
                                                  void
1 error generated.

Signed-off-by: Rama Bondan Prakoso <ramanarubp@gmail.com>

mtk: mtk_wcn_consys_hw: Fix a function declaration without a prototype is deprecated

../kernel/drivers/misc/mediatek/connectivity/common/common_main/platform/mtk_wcn_consys_hw.c:790:43: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct pinctrl *mtk_wcn_consys_get_pinctrl()
                                          ^
                                           void
1 error generated.

Signed-off-by: Rama Bondan Prakoso <ramanarubp@gmail.com>

mtk: perf_tracker: a function declaration without a prototype is deprecated

../kernel/drivers/misc/mediatek/perf/perf_tracker.c:190:43: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) get_cur_vcore_uv()
                                          ^
                                           void
../kernel/drivers/misc/mediatek/perf/perf_tracker.c:195:42: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) get_cur_ddr_khz()
                                         ^
                                          void
2 errors generated.

Signed-off-by: Rama Bondan Prakoso <ramanarubp@gmail.com>

mtk: display_recorder: Fix a function declaration without a prototype is deprecated

/kernel/drivers/misc/mediatek/video/mt6785/dispsys/display_recorder.c:1110:33: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
char *dprec_logger_get_dump_addr()
                                ^
                                 void
1 error generated.

Signed-off-by: Rama Bondan Prakoso <ramanarubp@gmail.com>